# ATOMBOX — POC d interface (RM2937). Site STATIQUE : pas de PHP.

<Virtualhost *:80>
DocumentRoot "/home/siteadm/atombox/public/dev"
ServerName atombox.dev.iprospective.fr
ServerAdmin webmaster@iprospective.fr

CustomLog /var/log/apache2/atombox_dev.access.log common
ErrorLog /var/log/apache2/atombox_dev.error.log

<Directory "/home/siteadm/atombox/public/dev">
        Require all granted
        Options -Indexes +FollowSymLinks
        AllowOverride None
</Directory>
</Virtualhost>

<Virtualhost *:443>
DocumentRoot "/home/siteadm/atombox/public/dev"
ServerName atombox.dev.iprospective.fr
ServerAdmin webmaster@iprospective.fr

CustomLog /var/log/apache2/atombox_dev.access.log common
ErrorLog /var/log/apache2/atombox_dev.error.log

SSLEngine on
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile    /etc/letsencrypt/live/dev.iprospective.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/dev.iprospective.fr/privkey.pem

<Directory "/home/siteadm/atombox/public/dev">
        Require all granted
        Options -Indexes +FollowSymLinks
        AllowOverride None
</Directory>
</Virtualhost>
